### ISSUE TITLE
The make -j$(nproc) sim command does not work in my Ubuntu environment

### ISSUE THREAD

**Issue by mrvalido** [bsc-loca/core_tile#1]
Dear,

I have tried to simulate Sargantana following the instructions of the project.
Theoretically I have installed the tools, gcc, verilator, riscv-gnu-toolchain...but when I run the command make -j$(nproc) sim...it gives the following error. configure: error: Could not link against boost_system !
**tools**

1. Ubuntu 20.04.6 LTS
2. Verilator 5.016 2023-09-16 rev v5.014-149-g57c816f90
3. gcc and g++ (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
4. riscv-gnu toolchain: 
    4.1 cloned from https://github.com/riscv-collab/riscv-gnu-toolchain, Installation (Newlib) :./configure --prefix=/opt/riscv ; make

the make linux option I did it first but I couldn't find the elf executables. and for that reason I had to install the newlib

thanks
Manuel
Universidad de La Laguna

build output _**make -j$(nproc) sim.**_
mkdir -p /home/zacarias/RISCV/core_tile/simulator/bootrom/build
mkdir -p /home/zacarias/RISCV/core_tile/simulator/reference/build/
dtc -I dts /home/zacarias/RISCV/core_tile/simulator/bootrom/ariane.dts -O dtb -o /home/zacarias/RISCV/core_tile/simulator/bootrom/build/ariane.dtb
cd /home/zacarias/RISCV/core_tile/simulator/reference/build/ && ../riscv-isa-sim/configure
/home/zacarias/RISCV/core_tile/simulator/bootrom/ariane.dts:61.19-70.7: Warning (interrupts_property): /soc/uart@10000000: Missing interrupt-parent
/home/zacarias/RISCV/core_tile/simulator/bootrom/ariane.dts:71.20-77.7: Warning (interrupts_property): /soc/timer@18000000: Missing interrupt-parent
riscv64-unknown-elf-gcc -T/home/zacarias/RISCV/core_tile/simulator/bootrom/linker.ld /home/zacarias/RISCV/core_tile/simulator/bootrom/bootrom.S -I/home/zacarias/RISCV/core_tile/simulator/bootrom/build -nostdlib -nostartfiles -nodefaultlibs -static -Wl,--no-gc-sections -march=rv64imafd -o /home/zacarias/RISCV/core_tile/simulator/bootrom/build/bootrom.o
/home/zacarias/RISCV/core_tile/simulator/bootrom/bin2hex.py -w 128 /home/zacarias/RISCV/core_tile/simulator/bootrom/build/bootrom.o bootrom.hex
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for ar... ar
checking for ranlib... ranlib
checking for dtc... /usr/bin/dtc
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for a BSD-compatible install... /usr/bin/install -c
checking for ANSI C header files... (cached) yes
checking for __int128_t... yes
checking whether the linker accepts -Wl,--export-dynamic... yes
checking whether C++ compiler accepts -relocatable-pch... no
configure: configuring default subproject : fesvr
checking for pthread_create in -lpthread... yes
checking for struct statx.stx_ino... yes
checking for struct statx.stx_mnt_id... no
configure: configuring default subproject : riscv
checking for boostlib >= 1.53 (105300)... yes
checking whether the Boost::ASIO library is available... yes
checking for main in -lboost_system... yes
checking whether the Boost::Regex library is available... yes
configure: error: Could not link against boost_system !
make: *** [/home/zacarias/RISCV/core_tile/simulator/reference/spike.mk:7: /home/zacarias/RISCV/core_tile/simulator/reference/build/Makefile] Error 1

**Comment by ArnauBigas** [comment]
Hi!

It seems like you are missing some libraries in your system. Install them using `sudo apt-get install libboost-all-dev`, and try compiling the simulator again.

I hope that fixes your issue :)

**Comment by mrvalido** [comment]
Dear Arnau,
thank for your information.. I fixed the error to build the simulator.

Now I started with the simulation...
but I have some doubt, What is the path to binary, I have seen that in the
folder verilaror the folder build has been created.
thank in advance
Regards
Manuel

**Comment by mrvalido** [comment]
se me olvidó adjuntar el archivo de salida.. veo algunos warning..
perdon
graciass
M.

---------- Forwarded message ---------
De: MANUEL JESUS RODRIGUEZ VALIDO ***@***.***>
Date: mié, 21 feb 2024 a las 7:18
Subject: Re: [bsc-loca/core_tile] The make -j$(nproc) sim command does not
work in my Ubuntu environment (Issue #1)
To: bsc-loca/core_tile <
***@***.***>


Dear Arnau,
thank for your information.. I fixed the error to build the simulator.

Now I started with the simulation...
but I have some doubt, What is the path to binary, I have seen that in the
folder verilaror the folder build has been created.
thank in advance
Regards
Manuel

**Comment by ArnauBigas** [comment]
Sorry, if you reply messages via e-mail I cannot see the attached files.

If I'm understanding you correctly, you are seeing some warnings in the console while compiling. That is to be expected, as long as you get the simulator binary built.
