### ISSUE TITLE
Visualizing the pipeline with Konata

### ISSUE THREAD

**Issue by EmmaRamos98** [bsc-loca/core_tile#2]
We are simulating Sargantana with both Verilator and Questasim with the necessary options to generate the files in kanata format to visualize the pipeline. The files seem to be generated correctly but it is not possible to visualize them in the Konata viewer. The file header is: Kanata 0004

We are using Verilator version 5.016 and Questasim 2022.4, and Konata ver 0.39.0, Kojiro Izuoka and Ryota Shioya on Ubuntu 2020.4.

To generate the konata.txt file we add +konara_dump to the simulation command.
./simulator/questa/sim.sh -c -suppress 3999 +load=./benchmarks/benchmarks/vvadd.riscv +commit_log +konata_dump

Are there other options to consider when viewing the konata file?

Thanks

**Comment by ArnauBigas** [comment]
Hi!

We forgot to mention in the README that the only version of Konata supported is [v0.34](https://github.com/shioyadan/Konata/releases/tag/v0.34).

Sorry for the inconvenience. Let me know if this fixed your issue!

**Comment by EmmaRamos98** [comment]
Hi!

I installed the v0.34 version and now it is working.

Thanks

**Comment by ArnauBigas** [comment]
Glad to hear that! I am closing the issue :)
